Fix Change configuring content type header
futuredapp/FTAPIKit pull request #61
Opened 2021-01-22 09:12 UTC by MichalMartinu

Podle dokumentace by request neměl obsahovat `Content-Type` hlavičku. Aktuálně je přidávána ke každému request. Předpokládám, že by mělo stačit upravit pouze `EncodableEndpoint`, který hlavičku obsahovat může.

Problém byl s `PUT` a `REMOVE` requesty, které končily chybou `400 - Invalid JSON`, pokud neměli žádný obsah.

https://tools.ietf.org/html/rfc7231#section-3.1.1.5

2021-01-22 14:15 UTC, MichalMartinu commented
Sakra nemůžu přijít na to proč 🙈

<img width="646" alt="Snímek obrazovky 2021-01-22 v 10 33 43" src="https://user-images.githubusercontent.com/26277065/105501451-859df880-5cc4-11eb-9fc8-1fd1eb149eb2.png">

2021-01-24 09:08 UTC, mkj-is requested changes
Díky, jen bych byl trochu opatrný s tím vyhazováním kódu.

Tohle trochu narušuje možnost používat encoding do něčeho jiného než je JSON (například Protobuf nebo MessagePack).

Mělo by stačit přesunout volání té `configure` metody do toho `switch`, což jsi vlastně do jisté míry udělal.

2021-01-24 09:09 UTC, mkj-is commented
> Sakra nemůžu přijít na to proč 🙈
> 
> <img alt="Snímek obrazovky 2021-01-22 v 10 33 43" width="646" src="https://user-images.githubusercontent.com/26277065/105501451-859df880-5cc4-11eb-9fc8-1fd1eb149eb2.png">

Pody kontrolují metadata a funguje to dost nestabilně, tím se netrap. Pořeším to.

2021-01-24 14:49 UTC, mkj-is approved these changes

2021-01-26 12:11 UTC, mkj-is approved these changes

2021-01-26 12:11 UTC, merged